services:
  - type: web
    name: sustainable-fashion-ml
    runtime: python
    runtimeVersion: 3.11.9
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --workers 4 --worker-class sync --bind 0.0.0.0:$PORT app:app"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.11.9